"""Render a recorded UI flow as a Playwright spec (CLAUDE.md sections 8, 10).

The recorder produced a flow document and nothing consumed it, which made the
browser half of agent 3 a promise rather than a feature. This is the consumer.

Three decisions shape the output:

**The emitted spec asserts something.** A recording replayed with no assertions
is a click script: it passes as long as the selectors still resolve, which is
the weakest possible test. Every emitted spec installs a `pageerror` listener
and fails if the flow triggered an uncaught exception - a signal that is cheap,
never ambiguous, and exactly what the recorder already proved is worth watching
(it captured one on the fixture).

**Recorded secrets are read from the environment, never inlined.** The recorder
deliberately did not capture password values, so there is nothing to inline
even if that were acceptable; the spec reads `process.env` and fails loudly
with the variable's name if it is unset. A test that silently submits an empty
password would report an auth bug that does not exist.

**Nothing from the recording is interpolated as code.** Selectors and values
are attacker-influenced - they came from a page QAgent does not control - so
every one of them goes through `_js_string`, which produces a quoted JavaScript
string literal and nothing else.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

#: Playwright actions this emitter knows how to render. Anything else is
#: written as a commented-out step rather than dropped: a silently missing
#: step makes the spec pass for the wrong reason.
RENDERABLE = {"click", "fill", "select", "check", "submit"}

_NON_IDENTIFIER = re.compile(r"[^0-9a-zA-Z]+")


def _js_string(value: str) -> str:
    """A safe JavaScript string literal.

    `json.dumps` is the right tool: JSON string syntax is a subset of
    JavaScript's, so it escapes quotes, backslashes and control characters
    correctly, and it cannot emit anything but a string.
    """
    return json.dumps(str(value))


def _env_name(selector: str) -> str:
    """A stable environment-variable name for a redacted field."""
    cleaned = _NON_IDENTIFIER.sub("_", selector).strip("_").upper()
    return f"QAGENT_SECRET_{cleaned[:40] or 'VALUE'}"


def _test_name(flow: dict) -> str:
    start = str(flow.get("start_url") or "the application")
    return f"recorded flow against {start}"


@dataclass
class EmittedSpec:
    path: str
    content: str
    step_count: int
    #: Environment variables the spec needs before it can run. Surfaced rather
    #: than buried, because a spec that needs a secret nobody set will fail in
    #: a way that looks like an application bug.
    required_env: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "steps": self.step_count,
            "required_env": self.required_env,
            "bytes": len(self.content),
        }


_HEADER = """// Generated by QAgent from a recorded browser session.
//
// Do not edit by hand: re-record and regenerate with `qagent record-import`.
// This spec depends only on @playwright/test - not on QAgent - so it keeps
// working if QAgent is uninstalled.
//
//   npx playwright test
//
// QAGENT_BASE_URL overrides the recorded origin.{secrets_note}
import {{ expect, test }} from "@playwright/test";

const BASE_URL = process.env.QAGENT_BASE_URL ?? {base_url};

/**
 * Reads a value the recorder deliberately did not capture.
 *
 * Throws rather than defaulting to "": a spec that silently submits an empty
 * password reports an authentication bug that does not exist.
 */
function secret(name: string): string {{
  const value = process.env[name];
  if (!value) {{
    throw new Error(
      `${{name}} is not set. The recorder redacted this field; supply it from your secret store.`,
    );
  }}
  return value;
}}
"""


def _render_step(step: dict, indent: str = "  ") -> list[str]:
    kind = str(step.get("type", ""))
    selector = step.get("selector")
    lines: list[str] = []

    if step.get("fragile"):
        # Stated in the output, not just at import time: whoever debugs this
        # spec in six months is reading the file, not the CLI transcript.
        lines.append(
            f"{indent}// Fragile selector: recorded by position, so this breaks on the"
        )
        lines.append(f"{indent}// next CSS change. Add a data-testid to this element.")

    if not selector or kind not in RENDERABLE:
        lines.append(f"{indent}// Unsupported step {kind!r}; review and replace by hand.")
        return lines

    target = f"page.locator({_js_string(selector)})"

    if kind == "click":
        lines.append(f"{indent}await {target}.click();")
    elif kind == "fill":
        if step.get("redacted"):
            name = _env_name(selector)
            lines.append(f"{indent}await {target}.fill(secret({_js_string(name)}));")
        else:
            lines.append(f"{indent}await {target}.fill({_js_string(step.get('value') or '')});")
    elif kind == "select":
        lines.append(
            f"{indent}await {target}.selectOption({_js_string(step.get('value') or '')});"
        )
    elif kind == "check":
        method = "check" if str(step.get("value", "")).lower() == "true" else "uncheck"
        lines.append(f"{indent}await {target}.{method}();")
    elif kind == "submit":
        # A form submit is a press, not a click: the recorded element is the
        # form, and Playwright has no `form.submit()` that waits properly.
        lines.append(f"{indent}await {target}.press(\"Enter\");")

    return lines


def render_flow(flow: dict) -> EmittedSpec:
    """Turn one UI flow document into a Playwright spec."""
    steps = [s for s in (flow.get("steps") or []) if isinstance(s, dict)]
    required_env = sorted(
        {
            _env_name(s["selector"])
            for s in steps
            if s.get("redacted") and s.get("selector")
        }
    )

    secrets_note = ""
    if required_env:
        listed = ", ".join(required_env)
        secrets_note = (
            f"\n// Redacted while recording; set before running: {listed}"
        )

    body: list[str] = [
        _HEADER.format(
            base_url=_js_string(flow.get("start_url") or "http://localhost:3000"),
            secrets_note=secrets_note,
        ),
        "",
        f"test({_js_string(_test_name(flow))}, async ({{ page }}) => {{",
        "  // An uncaught exception during the flow is a defect, and it is the",
        "  // one assertion a recording can always make honestly.",
        "  const pageErrors: string[] = [];",
        '  page.on("pageerror", (error) => pageErrors.push(String(error)));',
        "",
        "  await page.goto(BASE_URL);",
        "",
    ]

    for step in steps:
        body.extend(_render_step(step))

    diagnostics = flow.get("diagnostics") or []
    if diagnostics:
        body.append("")
        body.append("  // Observed while recording - already a finding before this test existed:")
        for diagnostic in diagnostics[:5]:
            body.append(f"  //   {str(diagnostic)[:160]}")

    body.extend(
        [
            "",
            "  expect(pageErrors, `uncaught exception during the recorded flow`).toEqual([]);",
            "});",
            "",
        ]
    )

    return EmittedSpec(
        path="recorded.spec.ts",
        content="\n".join(body),
        step_count=len(steps),
        required_env=required_env,
    )


def emit(flow: dict, *, out_dir, dry_run: bool = False, filename: str | None = None) -> EmittedSpec:
    """Write the spec, or report what would be written."""
    spec = render_flow(flow)
    if filename:
        spec = EmittedSpec(
            path=filename,
            content=spec.content,
            step_count=spec.step_count,
            required_env=spec.required_env,
        )

    if not dry_run:
        target = out_dir / spec.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(spec.content, encoding="utf-8")

    logger.info(
        "emitted a Playwright spec with %d step(s)%s",
        spec.step_count,
        " (dry run)" if dry_run else "",
    )
    return spec
