"""Render generated cases as pytest files (CLAUDE.md section 8, agent 3).

The generator has always produced declarative documents rather than code, and
that stays the right default: a document is diffable, reviewable, safe to run
without `eval`, and it is what the runner, the triage stage and the eval harness
all consume. This module is the other half of the promise the generator's
docstring has always made - that the same document "can be rendered to Playwright
or pytest later without regenerating anything".

Emitting files matters because a test that only exists inside QAgent is a test
the developer cannot run, step through, or keep after they stop using QAgent.
The emitted suite has no dependency on this package at all: it is `httpx` and
`pytest`, and it works if QAgent is uninstalled tomorrow.

Every value that reaches the output goes through `repr()`. Nothing from a spec
is ever interpolated into an executable position as raw text - a path of
``/x"); import os; os.system("rm -rf /`` renders as a harmless string literal,
because the only thing that ever gets formatted into the template is the result
of `repr` on a plain Python value.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

from qagent.modules.generator.rules import GeneratedCase

logger = logging.getLogger(__name__)

_NON_IDENTIFIER = re.compile(r"[^0-9a-zA-Z]+")

_MODULE_HEADER = '''"""Generated by QAgent from the discovered API surface.

Do not edit by hand: regenerate with `qagent emit`. These tests depend only on
pytest and httpx, so they keep working if QAgent is uninstalled.

Point them at a running application with QAGENT_BASE_URL, and supply auth with
QAGENT_AUTH_HEADER (for example "Authorization: Bearer ...").
"""

from __future__ import annotations

import os
import re

import httpx
import pytest

BASE_URL = os.environ.get("QAGENT_BASE_URL", {base_url!r}).rstrip("/")
TIMEOUT = float(os.environ.get("QAGENT_TIMEOUT", "30"))


def _auth_headers() -> dict[str, str]:
    raw = os.environ.get("QAGENT_AUTH_HEADER", "")
    if not raw or ":" not in raw:
        return {{}}
    name, _, value = raw.partition(":")
    return {{name.strip(): value.strip()}}


@pytest.fixture(scope="module")
def client():
    with httpx.Client(base_url=BASE_URL, timeout=TIMEOUT) as c:
        yield c


def _request(client, method, path, path_params, query, body, headers, authed):
    for name, value in (path_params or {{}}).items():
        path = path.replace("{{" + name + "}}", str(value))
    sent = dict(headers or {{}})
    if authed:
        sent.update(_auth_headers())
    return client.request(method, path, params=query or None, json=body, headers=sent)
'''


@dataclass
class EmittedFile:
    path: str
    content: str
    case_count: int

    def to_dict(self) -> dict:
        return {"path": self.path, "cases": self.case_count, "bytes": len(self.content)}


@dataclass
class EmissionReport:
    files: list[EmittedFile] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)

    @property
    def case_count(self) -> int:
        return sum(f.case_count for f in self.files)

    def to_dict(self) -> dict:
        return {
            "files": [f.to_dict() for f in self.files],
            "cases": self.case_count,
            "skipped": self.skipped,
        }


def _identifier(text: str, *, fallback: str = "case") -> str:
    """A safe Python identifier derived from a case name.

    Names come from generated case titles, which contain slashes, braces and
    quotes. This is what keeps them out of the emitted source as anything other
    than a comment.
    """
    cleaned = _NON_IDENTIFIER.sub("_", text).strip("_").lower()
    cleaned = re.sub(r"_+", "_", cleaned)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"{fallback}_{cleaned}" if cleaned else fallback
    return cleaned[:80]


def module_name_for(case: GeneratedCase) -> str:
    """Group cases into files the way CLAUDE.md section 8 draws them.

    ``tests/auth/login.spec.ts`` in the plan becomes ``test_auth.py`` here: one
    module per API module, which is the same grouping the planner and the
    dashboard use. A single 4,000-line file would be technically equivalent and
    useless to review.
    """
    key = case.endpoint_key or ""
    path = key.split(" ", 1)[-1] if " " in key else key
    for segment in path.strip("/").split("/"):
        lowered = segment.lower()
        if not segment or lowered in {"api", "v1", "v2", "v3"} or segment.startswith("{"):
            continue
        return _identifier(lowered, fallback="root")
    return "root"


def _assertion_lines(assertion: dict) -> list[str]:
    """Render one declarative assertion as executable pytest.

    Unknown types become an explicit failure rather than silently passing. A
    generated suite that quietly skips the assertion it could not render is a
    suite that reports green for the wrong reason.
    """
    kind = assertion.get("type", "unknown")
    value = assertion.get("value")

    if kind == "status_in":
        return [
            f"    assert response.status_code in {list(value or [])!r}, (",
            f"        f\"expected status in {list(value or [])!r}, got {{response.status_code}}\"",
            "    )",
        ]
    if kind == "status_not_in":
        forbidden = list(value or [])
        return [
            f"    assert response.status_code not in {forbidden!r}, (",
            f'        f"status {{response.status_code}} must not be one of {forbidden!r}"',
            "    )",
        ]
    if kind == "body_matches":
        return [
            f"    assert re.search({value!r}, response.text, re.IGNORECASE), (",
            f"        \"body should match /{{}}/\".format({value!r})",
            "    )",
        ]
    if kind == "body_not_matches":
        return [
            f"    assert not re.search({value!r}, response.text, re.IGNORECASE), (",
            f"        \"body must not match /{{}}/\".format({value!r})",
            "    )",
        ]
    if kind == "header_present":
        return [
            f"    assert {str(value).lower()!r} in "
            "{k.lower() for k in response.headers}, (",
            f"        \"response should carry header {value!r}\"",
            "    )",
        ]
    if kind == "latency_under_ms":
        return [
            f"    assert response.elapsed.total_seconds() * 1000 <= {value!r}, (",
            f"        f\"response should arrive within {value!r}ms\"",
            "    )",
        ]
    if kind == "json_path_exists":
        return [
            f"    assert _json_path(response.json(), {str(value)!r})[0], (",
            f"        \"response should contain path {str(value)!r}\"",
            "    )",
        ]
    if kind == "json_path_equals":
        path = assertion.get("path", "")
        return [
            f"    found, actual = _json_path(response.json(), {str(path)!r})",
            f"    assert found and actual == {value!r}, (",
            f"        f\"{path!r} should equal {value!r}, got {{actual!r}}\"",
            "    )",
        ]

    return [
        f"    pytest.fail({f'QAgent could not render assertion type {kind!r}'!r})",
    ]


_JSON_PATH_HELPER = '''

def _json_path(payload, path):
    """Walk a dotted path, mirroring the runner's own resolution."""
    current = payload
    for part in str(path).split("."):
        if isinstance(current, dict) and part in current:
            current = current[part]
        elif isinstance(current, list) and part.isdigit() and int(part) < len(current):
            current = current[int(part)]
        else:
            return False, None
    return True, current
'''


def render_case(case: GeneratedCase, *, used_names: set[str]) -> str:
    spec = case.spec or {}
    request = spec.get("request") or {}
    assertions = spec.get("assertions") or []

    name = _identifier(case.name, fallback="case")
    # Two rules can produce similar names for the same endpoint; a duplicate
    # def would silently shadow the earlier test rather than fail.
    candidate = f"test_{name}"
    suffix = 2
    while candidate in used_names:
        candidate = f"test_{name}_{suffix}"
        suffix += 1
    used_names.add(candidate)

    lines = [
        "",
        "",
        f"def {candidate}(client):",
        f"    {case.name!r}",
    ]
    if case.rationale:
        lines.append(f"    # {case.rationale}")
    if spec.get("expectation"):
        lines.append(f"    # Expect: {spec['expectation']}")

    lines += [
        "    response = _request(",
        "        client,",
        f"        {str(request.get('method', 'GET')).upper()!r},",
        f"        {str(request.get('path', '/'))!r},",
        f"        {dict(request.get('path_params') or {})!r},",
        f"        {dict(request.get('query') or {})!r},",
        f"        {request.get('json')!r},",
        f"        {dict(request.get('headers') or {})!r},",
        f"        authed={str(request.get('auth', 'default')) != 'none'!r},",
        "    )",
    ]

    for assertion in assertions:
        lines.extend(_assertion_lines(assertion))

    if not assertions:
        lines.append("    assert response.status_code < 500")

    return "\n".join(lines) + "\n"


def emit(
    cases: list[GeneratedCase], *, base_url: str, out_dir: Path, dry_run: bool = False
) -> EmissionReport:
    """Write one pytest module per API module.

    Returns the report whether or not anything was written, so ``--dry-run`` and
    a real emit produce the same summary and can be compared.
    """
    report = EmissionReport()
    if not cases:
        report.skipped.append("no cases to emit")
        return report

    grouped: dict[str, list[GeneratedCase]] = {}
    for case in cases:
        grouped.setdefault(module_name_for(case), []).append(case)

    needs_json_path = {"json_path_exists", "json_path_equals"}

    for module, module_cases in sorted(grouped.items()):
        used_names: set[str] = set()
        body = "".join(render_case(c, used_names=used_names) for c in module_cases)

        uses_json_path = any(
            a.get("type") in needs_json_path
            for c in module_cases
            for a in (c.spec or {}).get("assertions") or []
        )

        content = _MODULE_HEADER.format(base_url=base_url)
        if uses_json_path:
            content += _JSON_PATH_HELPER
        content += body

        file_path = f"test_{module}.py"
        report.files.append(
            EmittedFile(path=file_path, content=content, case_count=len(module_cases))
        )

        if not dry_run:
            target = out_dir / file_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    logger.info(
        "emitted %d case(s) across %d file(s)%s",
        report.case_count,
        len(report.files),
        " (dry run)" if dry_run else "",
    )
    return report
