/**
 * Records what the user does on the page (CLAUDE.md section 10).
 *
 * The only interesting engineering here is `buildSelector`. A recorder that
 * emits `body > div:nth-child(3) > div > button` produces tests that break on
 * the next CSS refactor, which is precisely the failure the self-healing
 * engine (modules/browser/healing.py) exists to clean up after. So the
 * priority order below is deliberately the same one healing.py scores
 * against: the most semantically stable attribute wins, and a positional path
 * is the last resort rather than the default.
 *
 * Nothing is sent anywhere from this file. It posts events to the service
 * worker, which is the only place that holds a recording.
 */

(() => {
  if (window.__qagentRecorderInstalled) return;
  window.__qagentRecorderInstalled = true;

  let recording = false;

  /** Attributes in descending order of how well they survive a refactor. */
  const STABLE_ATTRS = [
    "data-testid",
    "data-test",
    "data-cy",
    "aria-label",
    "name",
    "placeholder",
    "title",
  ];

  const cssEscape = (value) =>
    window.CSS && CSS.escape ? CSS.escape(value) : String(value).replace(/["\\]/g, "\\$&");

  /** True when a selector matches exactly one element, which is the only
   *  condition under which it is safe to record. */
  function isUnique(selector) {
    try {
      return document.querySelectorAll(selector).length === 1;
    } catch {
      return false;
    }
  }

  function buildSelector(el) {
    if (!el || el.nodeType !== 1) return null;

    for (const attr of STABLE_ATTRS) {
      const value = el.getAttribute(attr);
      if (value) {
        const candidate = `[${attr}="${value.replace(/"/g, '\\"')}"]`;
        if (isUnique(candidate)) return candidate;
      }
    }

    // An id generated by a framework (`:r3:`, `mui-4821`) is unique today and
    // different on the next render, so ids that look generated are skipped
    // rather than trusted.
    const id = el.getAttribute("id");
    if (id && !/^(:|.*\d{3,})/.test(id)) {
      const candidate = `#${cssEscape(id)}`;
      if (isUnique(candidate)) return candidate;
    }

    // Buttons and links are usually identified by what they say, and their
    // text is far more stable than their position.
    const text = (el.textContent || "").trim();
    if (text && text.length <= 40 && ["BUTTON", "A"].includes(el.tagName)) {
      const sameText = Array.from(document.querySelectorAll(el.tagName)).filter(
        (other) => (other.textContent || "").trim() === text,
      );
      if (sameText.length === 1) {
        return `${el.tagName.toLowerCase()}:has-text("${text.replace(/"/g, '\\"')}")`;
      }
    }

    const role = el.getAttribute("role");
    if (role) {
      const candidate = `${el.tagName.toLowerCase()}[role="${role}"]`;
      if (isUnique(candidate)) return candidate;
    }

    return positionalSelector(el);
  }

  /** Last resort. Recorded with `fragile: true` so the generated test can say
   *  so rather than pretending every selector is equally trustworthy. */
  function positionalSelector(el) {
    const parts = [];
    let node = el;
    while (node && node.nodeType === 1 && parts.length < 5) {
      let part = node.tagName.toLowerCase();
      const parent = node.parentElement;
      if (parent) {
        const siblings = Array.from(parent.children).filter((c) => c.tagName === node.tagName);
        if (siblings.length > 1) part += `:nth-of-type(${siblings.indexOf(node) + 1})`;
      }
      parts.unshift(part);
      if (node.id && !/^(:|.*\d{3,})/.test(node.id)) {
        parts[0] = `#${cssEscape(node.id)}`;
        break;
      }
      node = parent;
    }
    return parts.join(" > ");
  }

  function describe(el) {
    const selector = buildSelector(el);
    return {
      selector,
      fragile: Boolean(selector && selector.includes(">")),
      tag: el.tagName ? el.tagName.toLowerCase() : null,
      inputType: el.getAttribute ? el.getAttribute("type") : null,
      role: el.getAttribute ? el.getAttribute("role") : null,
      testid: el.getAttribute ? el.getAttribute("data-testid") : null,
      text: (el.textContent || "").trim().slice(0, 80) || null,
    };
  }

  /** Values that must never leave the browser. A recorded password replayed
   *  in CI is a credential in a log, in an artifact, and in a bug report. */
  function isSecret(el) {
    const type = (el.getAttribute("type") || "").toLowerCase();
    const name = `${el.getAttribute("name") || ""} ${el.getAttribute("id") || ""}`.toLowerCase();
    return (
      type === "password" ||
      el.getAttribute("autocomplete") === "current-password" ||
      /pass|secret|token|otp|cvv|card/.test(name)
    );
  }

  function emit(action) {
    if (!recording) return;
    chrome.runtime.sendMessage({
      type: "qagent:action",
      action: { ...action, url: location.href, at: Date.now() },
    });
  }

  document.addEventListener(
    "click",
    (event) => {
      const el = event.target.closest("a, button, [role='button'], input, select, label, summary");
      if (!el) return;
      emit({ type: "click", target: describe(el) });
    },
    true,
  );

  document.addEventListener(
    "change",
    (event) => {
      const el = event.target;
      if (!el || !el.tagName) return;
      const target = describe(el);
      if (isSecret(el)) {
        // The interaction is recorded; the value is not. A generated test gets
        // a placeholder the developer fills from a secret store.
        emit({ type: "fill", target, value: null, redacted: true });
        return;
      }
      if (el.tagName === "SELECT") {
        emit({ type: "select", target, value: el.value });
      } else if (["checkbox", "radio"].includes((el.getAttribute("type") || "").toLowerCase())) {
        emit({ type: "check", target, value: String(el.checked) });
      } else {
        emit({ type: "fill", target, value: (el.value || "").slice(0, 200) });
      }
    },
    true,
  );

  document.addEventListener(
    "submit",
    (event) => emit({ type: "submit", target: describe(event.target) }),
    true,
  );

  // Console errors observed during the session are evidence: a recorded flow
  // that logs an uncaught TypeError has already found something.
  const originalError = console.error;
  console.error = function (...args) {
    emit({ type: "console_error", message: args.map(String).join(" ").slice(0, 500) });
    return originalError.apply(this, args);
  };

  window.addEventListener("error", (event) =>
    emit({ type: "page_error", message: String(event.message).slice(0, 500) }),
  );

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message.type === "qagent:set-recording") {
      recording = Boolean(message.recording);
      sendResponse({ ok: true, recording });
    }
    return true;
  });

  // A tab that loads mid-recording has to learn the current state.
  chrome.runtime.sendMessage({ type: "qagent:hello" }, (response) => {
    if (response && typeof response.recording === "boolean") recording = response.recording;
  });
})();
