"""bug history, repositories, gates, deployments, notifications

Revision ID: 65768a1f00d2
Revises: 807023a326dd
Create Date: 2026-09-21 03:30:44.375385
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '65768a1f00d2'
down_revision: str | None = '807023a326dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_index('ix_notifications_status_created', 'notifications', ['status', 'created_at'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('subdirectory', sa.String(length=300), nullable=True),
    sa.Column('secret_ref', sa.String(length=200), nullable=True),
    sa.Column('last_analyzed_sha', sa.String(length=64), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url', name='uq_repository_project_url')
    )
    op.create_index(op.f('ix_repositories_org_id'), 'repositories', ['org_id'], unique=False)
    op.create_index(op.f('ix_repositories_project_id'), 'repositories', ['project_id'], unique=False)
    op.create_table('quality_gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_gates_commit_sha'), 'quality_gates', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_quality_gates_org_id'), 'quality_gates', ['org_id'], unique=False)
    op.create_index('ix_quality_gates_project_created', 'quality_gates', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quality_gates_project_id'), 'quality_gates', ['project_id'], unique=False)
    op.create_index(op.f('ix_quality_gates_run_id'), 'quality_gates', ['run_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('quality_gate_id', sa.UUID(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quality_gate_id'], ['quality_gates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_commit_sha'), 'deployments', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_deployments_org_id'), 'deployments', ['org_id'], unique=False)
    op.create_index('ix_deployments_project_created', 'deployments', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_table('bug_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('bug_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bug_comments_bug_created', 'bug_comments', ['bug_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bug_comments_bug_id'), 'bug_comments', ['bug_id'], unique=False)
    op.create_index(op.f('ix_bug_comments_org_id'), 'bug_comments', ['org_id'], unique=False)
    op.create_table('bug_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('bug_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('from_value', sa.String(length=64), nullable=True),
    sa.Column('to_value', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bug_events_bug_created', 'bug_events', ['bug_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bug_events_bug_id'), 'bug_events', ['bug_id'], unique=False)
    op.create_index(op.f('ix_bug_events_org_id'), 'bug_events', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_events_org_id'), table_name='bug_events')
    op.drop_index(op.f('ix_bug_events_bug_id'), table_name='bug_events')
    op.drop_index('ix_bug_events_bug_created', table_name='bug_events')
    op.drop_table('bug_events')
    op.drop_index(op.f('ix_bug_comments_org_id'), table_name='bug_comments')
    op.drop_index(op.f('ix_bug_comments_bug_id'), table_name='bug_comments')
    op.drop_index('ix_bug_comments_bug_created', table_name='bug_comments')
    op.drop_table('bug_comments')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_index('ix_deployments_project_created', table_name='deployments')
    op.drop_index(op.f('ix_deployments_org_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_commit_sha'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_quality_gates_run_id'), table_name='quality_gates')
    op.drop_index(op.f('ix_quality_gates_project_id'), table_name='quality_gates')
    op.drop_index('ix_quality_gates_project_created', table_name='quality_gates')
    op.drop_index(op.f('ix_quality_gates_org_id'), table_name='quality_gates')
    op.drop_index(op.f('ix_quality_gates_commit_sha'), table_name='quality_gates')
    op.drop_table('quality_gates')
    op.drop_index(op.f('ix_repositories_project_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_org_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index('ix_notifications_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
