"""planner coverage and repository rag

Adds what the Test Planner (agent 2) and repository RAG need: the plan and its
plan-vs-actual coverage on each run, and the `code_chunks` table that lets an
index outlive the worker process that built it.

Revision ID: 807023a326dd
Revises: be76ba4d4b4c
Create Date: 2026-09-20 10:23:54.282844
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '807023a326dd'
down_revision: str | None = 'be76ba4d4b4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_commit_sha'), 'code_chunks', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_code_chunks_digest'), 'code_chunks', ['digest'], unique=False)
    op.create_index(op.f('ix_code_chunks_org_id'), 'code_chunks', ['org_id'], unique=False)
    op.create_index('ix_code_chunks_project_digest', 'code_chunks', ['project_id', 'digest'], unique=True)
    op.create_index(op.f('ix_code_chunks_project_id'), 'code_chunks', ['project_id'], unique=False)
    # server_default is load-bearing: ADD COLUMN ... NOT NULL with no default
    # fails outright on a table that already holds rows, which is every database
    # this migration exists to upgrade. The default is then dropped, so new rows
    # get their value from the mapper rather than from the schema - two sources
    # for one default is how they drift apart.
    op.add_column('test_runs', sa.Column('plan', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('test_runs', sa.Column('coverage', sa.JSON(), nullable=False, server_default='{}'))
    op.alter_column('test_runs', 'plan', server_default=None)
    op.alter_column('test_runs', 'coverage', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'coverage')
    op.drop_column('test_runs', 'plan')
    op.drop_index(op.f('ix_code_chunks_project_id'), table_name='code_chunks')
    op.drop_index('ix_code_chunks_project_digest', table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_org_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_digest'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_commit_sha'), table_name='code_chunks')
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
