"""per-project notification config

Where a project's alerts go. Per project rather than per deployment because the
platform is multi-tenant: one org's defects must not page another org's channel.

Revision ID: 9c9e12caf320
Revises: 65768a1f00d2
Create Date: 2026-09-21 15:32:00.645666
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9c9e12caf320'
down_revision: str | None = '65768a1f00d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, then dropped - the same trap as the planner columns:
    # ADD COLUMN ... NOT NULL with no default fails on a table that already has
    # rows, which is every database this migration exists to upgrade. Dropping
    # the default afterwards keeps the mapper the single source of it.
    op.add_column(
        'projects', sa.Column('notify', sa.JSON(), nullable=False, server_default='{}')
    )
    op.alter_column('projects', 'notify', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'notify')
    # ### end Alembic commands ###
